### ISSUE TITLE
module.exports statement causes non-CJS projects to break

### ISSUE THREAD

**Issue by hiebj** [Neohapsis/angular-bootstrap-npm#1]
The module.exports statement inserted by the gulpfile at the end of angular-ui-bootstrap causes projects that do not use a CJS-based dependency management system to break.

I am using your npm project to provide angular-ui-bootstrap, because I do not use browserify or bower and angular-ui does not currently maintain a prebuilt npm package from which the latest versions can be easily included. I use npm as my only package manager and Gulp.js to build my project, so there is no "module" variable declared in my namespace. As a result, when I include your angular-bootstrap.min.js file in my project, it breaks with

```
ReferenceError: module is not defined
```

This can be fixed in several ways while still maintaining your adherence to CJS; for instance, in my own project I successfully built a working version of your project by changing the line from

```
module.exports='ui.bootstrap';
```

to

```
if (typeof module !== 'undefined') module.exports = 'ui.bootstrap';
```

There are several other ways to avoid a problem like this. If there is another way that you would prefer to fix it, please do. Otherwise I am happy to create a pull request with this change to your gulpfile.

Unfortunately, until this is fixed I have to use angular-bootstrap-temporary, which uses an outdated version of angular-ui-bootstrap. It's critical for deployment reasons that there not be any hackish steps to work around something like this, and that other developers can just run npm-install in my project to get up and running.

**Comment by jusopi** [comment]
I added this fix to version 0.12.3 - fb079389c46cd1f91b5b5b69e874f6bb909a5390.  It has also been published to NPM.  

I didn't quite understand how/why you're using an NPM-specific package in a non-CJS project but since this request was trivial, I didn't see an issue adding it.  However if it does prove to be problematic down the road, I may create a special branch for the non-CJS requests.  Let me know if it works please.  Thank you.
