### ISSUE TITLE
include full tpls?

### ISSUE THREAD

**Issue by olsonpm** [Neohapsis/angular-bootstrap-npm#3]
I would like to add a dependency without downloads, or custom builds.  Is there a reason you didn't include the full templates in the dist off the bat?  Would you be against accepting a PR to include those optionally via require('angular-bootstrap-npm')({ includeFullTpls: true })?

Thanks much

**Comment by jusopi** [comment]
If I understand you correctly, then i wouldn't have an issue with that since some people might want access to modify the templates/css.  I'm thinking you'd probably want to select a _template-less_ module like `require('angular-bootstrap-npm/dist/angular-bootstrap-no-tmpls')` and then whatever your subsequent method would be?

Please go ahead and send the PR.

**Comment by olsonpm** [comment]
I see.  Your method would be a non-breaking change.  Just to make sure we're on the same page:

### Your method:

 - Have /dist/ contain 4 js files:

```
   angular-bootstrap.js
   angular-bootstrap.min.js
   angular-bootstrap-full-tpls.js
   angular-bootstrap-full-tpls.min.js
```

By default require('angular-bootstrap-npm') would activate angular-bootstrap.js
If you wanted the full-tpls version, then one would require('/node_modules/angular-bootstrap-npm/dist/angular-bootstrap-full-tpls.js')

### My method

 - Dist would also contain the above 4 js files
 - In package.json, main would point to a new file /index.js
 - index.js would export a function like the following:

``` javascript
module.exports = function(argsObj) {
  var includeFullTpls = (typeof argsObj.includeFullTpls === 'undefined')
    ? false
    : argsObj.includeFullTpls;

  if (includeFullTpls) {
    require('/dist/angular-bootstrap-full-tpls.js');
  } else {
    require('/dist/angular-bootstrap.js');
  }

  return ({ ver: '#0.12.0' });
}
```

Let me know your thoughts and I'll create a PR.

**Comment by jusopi** [comment]
I think what I'm not understanding is that the current bootstrap assets I am pulling have the templates embedded in the dist javascript files.  If you look towards the bottom, it's utilizing `$templateCache`.  

So would what you're proposing have a separate folder for the actual _template.html_ files?  Those files somehow would be dumped into the dist folder as well?  Sorry for the confusion, just really want to fully understand your issue and the proposal regarding the actual template files themselves.

**Comment by olsonpm** [comment]
Ah okay, well I looked at 0.12.0 and it's not there:

https://github.com/Neohapsis/angular-bootstrap-npm/blob/0.12.0/dist/angular-bootstrap.js#L3903

but I see them in master.  Either way, I think dist should include both versions and mimic angular-ui/bootstrap.  What doesn't matter to me is how people reference them, whether via a require function or hardcoding the path (which isn't a problem because it should never change).

**Comment by jusopi** [comment]
Once before I was actually pulling their library and building it.  But at some point their dependencies were not playing well with my system and I thought, "why not just download it and add what I need".  Ergo the `curl` task in the gulp file.  I'd prefer to just keep it as is in terms of **how** they reference which version they want.  Since they have just released an update, I will see about pulling those other builds from them.  

So regarding the _non_-`$templateCache`ing version that we'd include, how do you propose those people gain access to the actual html templates if they're not compiled into the js files?  I ask only because i have never used anything but the compiled version of the library.

**Comment by olsonpm** [comment]
Makes sense

And funny you ask about accessing the templates for the non-cached versions.  Angular's official repo responded to that question:
https://github.com/angular-ui/bootstrap/issues/4260

In short, their stance is there should be no need to reference the html template files.  The workflow instead should be to reference the `-tpls` script and override the directive's templateCache path.

Their solution works fine, it could just be confusing a month down the road when the templateCache key to a file doesn't correspond to the actual file structure.

To keep it simple, my proposal would be to include the html templates in your `dist` folder, preserving the angular-ui/bootstrap `template` directory structure.  This would allow developers to consume them if they choose to do so.

On a separate note, I did just remember why I wasn't using the official repo - they don't have version 0.12.0 which a project I'm working with depends on.  Considering their newer versions [are all on npm](https://www.npmjs.com/package/angular-ui-bootstrap) though, mind explaining why you choose to upkeep this one?

**Comment by jusopi** [comment]
> To keep it simple, my proposal would be to include the html templates in your dist folder, preserving the angular-ui/bootstrap template directory structure. This would allow developers to consume them if they choose to do so.

Ok that sounds like a plan of attack. Will you submit the PR for that or should I implement?  I do want to use the `curl` approach rather than bringing in their project seeing as we're just copying files.  I'll handle the update to their recent release next week.

> On a separate note, I did just remember why I wasn't using the official repo - they don't have version 0.12.0 which a project I'm working with depends on. Considering their newer versions are all on their official repo though, mind explaining why you choose to upkeep this one?

There was some mixup/mess-up with tagging the various releases.  I'm not entirely sure what happened.  However the last few releases have been in lock-step with theirs.

**Comment by olsonpm** [comment]
Yeah I can send the PR.  I will be busy this weekend but can commit to having a PR by next week Thursday.

**Comment by olsonpm** [comment]
So I leave you with two branches:

1) Unfinished (only allows you to build a tpls or non-tpls version, doesn't output both)
2) Finished, but mangled your code a bit because I am not terribly familiar with streams

My intent is that you can choose whether to keep the code how you're familiar with and finish where I left off - or you can take the finished branch understanding the code changed quite a bit.

### Unfinished

https://github.com/olsonpm/angular-bootstrap-npm/tree/full-tpls

works like the following:

``` shell
gulp --ver 0.13.4
// outputs dist with the tpls files per default behavior

gulp --ver 0.13.4 --exclude-tpls
// outputs dist with the non-tpls version as well as the template directory from
//   angular-ui-bootstrap.  Downloading the template directory via svn
//   was the easiest way

// Note: my initial idea does not include a way to output both tpls and non-tpls versions
```

### Finished

The problem with my initial idea is that I didn't know how to cleanly allow the default build to build both the tpls and non-tpls versions.  Specifically, I don't know how to start a function after a stream finishes.  However I do know how to work with promises, and I am familiar with a library called stream-to-promise.  Hence I created a second branch:
https://github.com/olsonpm/angular-bootstrap-npm/tree/full-tpls-promises

``` shell
gulp --ver 0.13.4
// outputs dist with both tpls, non-tpls, and template directory
```

**Comment by jusopi** [comment]
Thanks for this.  I will look this over this weekend and give you an update on which way we should proceed.  Question for you:  Were you able to actually get their build process to complete?  After 0.12.1 (i think), I kept getting build failures, ergo why I switched to just downloading via curl.

**Comment by olsonpm** [comment]
Sounds good.

I don't understand what build process you're referencing, but their npm package includes both the tpls and non-tpls versions.  It doesn't come with the templates themselves, and they also didn't release version 0.12.0 which is what I need.

**Comment by jusopi** [comment]
Can you send me an email to _m8r-nhdq6f@mailinator.com_ with a way to contact you?  Then I will reach out, I think this bears more discussion than this medium will allow.

**Comment by jusopi** [comment]
ok so having chatted with @olsonpm the plan of attack for a solution is:
- in lieu of having a CDN URL to pull the template HTML files from, use Git to checkout the target version's branch.
- copy the `templates` folders over to the `dist` folder.
- update the `clean` gulp task to remove the Git repo folder
- use `curl` gulp task per current use case to download the javascript files.

**Comment by jusopi** [comment]
Ok so I did a test run on this in the branch - https://github.com/Neohapsis/angular-bootstrap-npm/tree/feature/include_full_tpls

It builds fine and I am able to target the proper version numbers via the build `gulp --ver=0.13.4`.  I haven't had a chance to test the non-template build files since I'm not entirely sure how to utilize them in a proper use case.  The issue with this is that people will most likely have to run a script to copy the _./dist/template_ folder to their desired source folder in order for the directives to pull from their respective templateUrls. 

Let me know if this works for your use case.  If so, we can close the issue and I will merge it back into the master branch and tag as `0.13.4-tpls` (or something).

**Comment by jusopi** [comment]
btw, naming convention for the js files are now somewhat mimicking how Bootstrap's CDN names their files.  The same applies to the minified files too.
- **angular-bootstrap-tpls.js** - template HTML cached via `$templateCache`. `package.json`'s main file points to this file.
- **angular-bootstrap.js** - doesn't have the template HTML cached via `$templateCache`

**Comment by olsonpm** [comment]
Awesome - looks good.  And the proper use case I see is symlinking to the defaults.  Assuming the folder structure stays the same, updating the version should automatically update the templates within the developer's app.

I'm looking into setting up a test case now

**Comment by jusopi** [comment]
Just checking in here.  @olsonpm did you happen to run your test cases?  If it's a go, I will go ahead and wrap up this bug and merge back into master.  Not sure how I am planning to tag this though.  I want to keep the semver versioning in lock-step with ui.bootstrap's version but I also need to denote the change somehow.  I'm thinking calling it `0.13.4-full-tpls`

**Comment by olsonpm** [comment]
Thanks for following up

My test case can be found here:
https://github.com/olsonpm/angularExample/tree/angular-bootstrap-npm

All you should have to do is run 'gulp serve', in the case you're interested.  It comes with livereload so playing around is easy.

**Comment by jusopi** [comment]
I wasn't able to get your test case up and running; it was missing some dependencies that were not specified in the `package.json`.  But I did test the whole thing in my current app and the files w/ the templates cached is working.  We don't have a use case for not using the default templates.  I am going to close this for now and merge and tag as `0.13.4-full-tpls`.  Then I will also do a tag for the new `0.14.0` since they just released.

**Comment by olsonpm** [comment]
Terribly sorry about that.  I definitely remember having the site up and running, and I alias 'npmis' to 'npm install --save ' so there's rarely a case I'm installing dependencies without saving them.

FWIW I updated the repo and tested just now with a fresh clone and it serves the site up on localhost:8081.  The only global dependency is gulp which I assume you have considering this repo.
