### ISSUE TITLE
Deprecated?

### ISSUE THREAD

**Issue by dolzenko** [Neohapsis/angular-bootstrap-npm#7]
Should this package be deprecated now as we have https://www.npmjs.com/package/angular-ui-bootstrap ?

**Comment by jusopi** [comment]
I wasn't aware that the official team supported NPM.  If they are I may stop supporting this or pass ownership to someone else.  No need in supporting both in parallel.  I will report back in the next few days.  Thanks for the heads up on this.

**Comment by jusopi** [comment]
Just an update on this issue: Now that it is being published by the original angular-ui team, I will no longer be supporting this aside from updating the README to point to their repo.  Iill also see about marking it as deprecated so that it shows when people search for it via the npm cli.  

Another user whom I've been in contact may decide to fork it since he specifically asked for a feature regarding the templates.  Once he does so, that too will be reflected in the README file.
